In [1]:
#this code here creates 100 batches from the anagrams dataset for the experiment. Each subject 
#sees 5 anagrams (1 anagram from each configuration with either 2 being hard, 3 being easy 
#or 3 being hard, 2 being easy)
from random import shuffle
import numpy as np
import random

In [122]:
#the original dataset which we will not change in the codes
anagrams_3o = ["THE", "WHY", "CAP", "YES", "CUP", "FUN", "EYE", "SUN", "HAT", "CAN"]
anagrams_3_shuffled_easyo = ["TEH", "WYH", "CPA", "YSE", "CPU","FNU", "EEY", "SNU", "HTA", "CNA"]
anagrams_3_shuffled_hardo = ["HTE", "HWY", "APC", "EYS", "PCU", "NUF", "YEE", "UNS", "AHT", "ACN"]
anagrams_4o = ["WORD", "DEED", "BELL", "SORT", "PINT", "BELT", "CARD", "FIND", "YELL", "COLD"]
anagrams_4_shuffled_easyo = ["WODR", "DDEE", "BLLE", "STRO", "PTIN", "BTEL", "CADR", "FNDI", "YLEL", "CDOL"]
anagrams_4_shuffled_hardo = ["OWDR", "EDDE", "LBLE", "TOSR", "TIPN", "TBLE", "RADC", "DIFN", "LYLE","DOCL"]
anagrams_5o = ["VEGAN", "CLERK", "POKER", "OASIS", "GIANT", "OPIUM", "DONOR", "PHONE", "ELECT", "SCALE"]
anagrams_5_shuffled_easyo = ["VENGA","CLREK","PEOKR","OSIAS","GIATN","OUIPM","DONRO","PHNEO","ECELT","SCELA"]
anagrams_5_shuffled_hardo = ["EVANG", "KLECR","KOERP","SAOSI","IGNAT","POUIM","OONRD","NPOHE","TELCE","ESALC"]
anagrams_6o = ["SHADOW", "DOLLAR", "RANDOM", "SALARY", "WEIGHT", "REFUND", "LETTER",  "CARBON", "WIZARD", "BALLET"]
anagrams_6_shuffled_easyo = ["SADOWH","DOLRLA","RAODNM","SALYRA","WEIGTH","RDFUNE","LEETTR","CRABON","WIZRAD","BLLAET"]
anagrams_6_shuffled_hardo = ["HSOADW", "RODLLA","MANROD","AALRYS","IEGWHT","UEFNDR","RETLET","NCRBOA","ZIAWRD","EABLLT"]
anagrams_7o = ["CLIMATE", "JAYWALK", "HAMMOCK", "DURABLE", "NAUGHTY", "GLACIER", "JUMBLED", "EXPLAIN", "GARBAGE", "JOURNEY"]
anagrams_7_shuffled_easyo = ["CLEIMAT ","JWAYALK","HAKMOCM","DURAELB","NAYUGHT","GLICAER","JLUMBED","EXPLIAN","GBRAAGE","JNOUREY"]
anagrams_7_shuffled_hardo = ["TCILAME","AYKAWLJ","CAMHOMK","EURADBL","AYUGNHT","CLAIGER","LUBMEJD","AXPLINE","BARAGGE","YUOEJRN"]

In [124]:
def rand_zero_one(): #function creates an array of size 5 with 0s and 1s -- the catch being number of either doesn't exceed by 3 and lessens by 2.
    arr = np.zeros(5)
    b = random.choice([2,3]) #either make 2 or 3 elements 1 randomly
    
    temp = np.asarray(arr)   # Cast to numpy array
    shape = temp.shape       # Store original shape
    temp = temp.flatten()    # Flatten to 1D
    inds = np.random.choice(temp.size, size=b)   # Get random indices of size b
    temp[inds] = 1                               # Fill with 1
    temp = temp.reshape(shape)                     # Restore original shape
    return temp #return the array -- this will have 2 (or 3) zeros and coversely 3 (or 2) ones at random positions

def rand_zero_one2(): #same function as above but we control the randomness
    
    arr = np.array([[1, 1, 1, 0, 0], [1, 0, 0, 0, 1], [1, 1, 0, 1, 0], 
                    [0, 1, 1, 1, 0], [0, 1, 1, 0, 1], [0, 0, 1, 1, 0],
                    [0, 0, 1, 1, 1], [0, 0, 0, 1, 1], [0, 0, 1, 0, 1],
                    [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 0, 1]])    
    
    temp = arr[np.random.choice(arr.shape[0], 1)]
    return temp[0] #return the array -- this will have 2 (or 3) zeros and coversely 3 (or 2) ones at random positions

In [125]:
while(np.sum(counter) < 500):
    
    #the dataset
    anagrams_3 = ["THE", "WHY", "CAP", "YES", "CUP", "FUN", "EYE", "SUN", "HAT", "CAN"]
    anagrams_3_shuffled_easy = ["TEH", "WYH", "CPA", "YSE", "CPU","FNU", "EEY", "SNU", "HTA", "CNA"]
    anagrams_3_shuffled_hard = ["HTE", "HWY", "APC", "EYS", "PCU", "NUF", "YEE", "UNS", "AHT", "ACN"]
    anagrams_4 = ["WORD", "DEED", "BELL", "SORT", "PINT", "BELT", "CARD", "FIND", "YELL", "COLD"]
    anagrams_4_shuffled_easy = ["WODR", "DDEE", "BLLE", "STRO", "PTIN", "BTEL", "CADR", "FNDI", "YLEL", "CDOL"]
    anagrams_4_shuffled_hard = ["OWDR", "EDDE", "LBLE", "TOSR", "TIPN", "TBLE", "RADC", "DIFN", "LYLE","DOCL"]
    anagrams_5 = ["VEGAN", "CLERK", "POKER", "OASIS", "GIANT", "OPIUM", "DONOR", "PHONE", "ELECT", "SCALE"]
    anagrams_5_shuffled_easy = ["VENGA","CLREK","PEOKR","OSIAS","GIATN","OUIPM","DONRO","PHNEO","ECELT","SCELA"]
    anagrams_5_shuffled_hard = ["EVANG", "KLECR","KOERP","SAOSI","IGNAT","POUIM","OONRD","NPOHE","TELCE","ESALC"]
    anagrams_6 = ["SHADOW", "DOLLAR", "RANDOM", "SALARY", "WEIGHT", "REFUND", "LETTER",  "CARBON", "WIZARD", "BALLET"]
    anagrams_6_shuffled_easy = ["SADOWH","DOLRLA","RAODNM","SALYRA","WEIGTH","RDFUNE","LEETTR","CRABON","WIZRAD","BLLAET"]
    anagrams_6_shuffled_hard = ["HSOADW", "RODLLA","MANROD","AALRYS","IEGWHT","UEFNDR","RETLET","NCRBOA","ZIAWRD","EABLLT"]
    anagrams_7 = ["CLIMATE", "JAYWALK", "HAMMOCK", "DURABLE", "NAUGHTY", "GLACIER", "JUMBLED", "EXPLAIN", "GARBAGE", "JOURNEY"]
    anagrams_7_shuffled_easy = ["CLEIMAT ","JWAYALK","HAKMOCM","DURAELB","NAYUGHT","GLICAER","JLUMBED","EXPLIAN","GBRAAGE","JNOUREY"]
    anagrams_7_shuffled_hard = ["TCILAME","AYKAWLJ","CAMHOMK","EURADBL","AYUGNHT","CLAIGER","LUBMEJD","AXPLINE","BARAGGE","YUOEJRN"]
    
    counter = np.zeros((10,10)) 
    batch = np.empty((100,5), dtype='object')
    answers = np.empty((100,5), dtype='object')

    c = -1

    for i in range(2000): #create n batches    

        q = rand_zero_one2() #get list of difficulties here i.e. whether the anagram will be 0 or 1 (size is 1X5)

        break_var = 0

        for j in range(5): #if any of the chosen lists is empty then continue the loop all together
            if q[j] == 0: #search from easy list if 0
                list1 = 'anagrams_'+str(j+3)+'_shuffled_easy'
                if len(eval(list1)) == 0:
                    break_var = 1
            elif q[j] == 1: #else search from hard list            
                list1 = 'anagrams_'+str(j+3)+'_shuffled_hard'
                if len(eval(list1)) == 0: #if list empty i.e. all elements have been covered 5 times
                    break_var = 1

        if break_var > 0: #just move on if any of the chosen lists was going to be empty
                continue

        c = c+1
        for j in range(5): #go through the anagram lists here            
            list2 = 'anagrams_'+str(j+3)        
            if q[j] == 0: #search from easy list if 0
                list1o = 'anagrams_'+str(j+3)+'_shuffled_easyo'
                list1 = 'anagrams_'+str(j+3)+'_shuffled_easy'         

                a = random.choice(range(len(eval(list1)))) #get random element from list            
                b = eval(list1o).index(eval(list1)[a])  #get index from original list           
                counter[j*2,b] = counter[j*2,b]+1 #increase counter size
                if counter[j*2,b] > 4:
                    eval(list1).pop(a) #remove element if it has been sampled more than 5 times
            elif q[j] == 1: #else search from hard list
                list1o = 'anagrams_'+str(j+3)+'_shuffled_hardo'
                list1 = 'anagrams_'+str(j+3)+'_shuffled_hard'

                a = random.choice(range(len(eval(list1)))) #get random element from list
                b = eval(list1o).index(eval(list1)[a])

                counter[j*2+1,b] = counter[j*2+1,b]+1
                if counter[j*2+1,b] > 4:
                    eval(list1).pop(a)

            batch[c,j] = eval(list1o)[b] #put the element in the batch
            answers[c,j] = eval(list2)[b] #get answers for the batch as well



In [126]:
print(np.sum(counter))
print(c)

500.0
99


In [127]:
print(counter)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [130]:
print(answers)

[['YES' 'BELL' 'OPIUM' 'WIZARD' 'NAUGHTY']
 ['FUN' 'FIND' 'OPIUM' 'WIZARD' 'JAYWALK']
 ['EYE' 'YELL' 'DONOR' 'SALARY' 'HAMMOCK']
 ['YES' 'CARD' 'CLERK' 'BALLET' 'GARBAGE']
 ['CAN' 'BELL' 'DONOR' 'REFUND' 'JOURNEY']
 ['YES' 'BELT' 'POKER' 'WIZARD' 'NAUGHTY']
 ['WHY' 'BELT' 'VEGAN' 'REFUND' 'GARBAGE']
 ['CAP' 'BELT' 'VEGAN' 'REFUND' 'JOURNEY']
 ['YES' 'YELL' 'PHONE' 'WEIGHT' 'JOURNEY']
 ['EYE' 'DEED' 'OPIUM' 'CARBON' 'NAUGHTY']
 ['HAT' 'YELL' 'VEGAN' 'DOLLAR' 'CLIMATE']
 ['CUP' 'WORD' 'GIANT' 'SHADOW' 'GLACIER']
 ['WHY' 'BELL' 'VEGAN' 'SHADOW' 'GARBAGE']
 ['THE' 'WORD' 'DONOR' 'DOLLAR' 'EXPLAIN']
 ['CAP' 'CARD' 'ELECT' 'BALLET' 'NAUGHTY']
 ['CAP' 'DEED' 'DONOR' 'CARBON' 'JAYWALK']
 ['FUN' 'PINT' 'DONOR' 'RANDOM' 'CLIMATE']
 ['FUN' 'SORT' 'VEGAN' 'CARBON' 'EXPLAIN']
 ['FUN' 'BELT' 'GIANT' 'WEIGHT' 'JAYWALK']
 ['WHY' 'SORT' 'OASIS' 'WIZARD' 'HAMMOCK']
 ['SUN' 'PINT' 'OPIUM' 'WEIGHT' 'JOURNEY']
 ['EYE' 'PINT' 'OPIUM' 'SHADOW' 'JOURNEY']
 ['EYE' 'FIND' 'SCALE' 'BALLET' 'HAMMOCK']
 ['THE' 'PI

In [131]:
print(batch)

[['YSE' 'BLLE' 'OUIPM' 'ZIAWRD' 'AYUGNHT']
 ['NUF' 'FNDI' 'OUIPM' 'ZIAWRD' 'JWAYALK']
 ['YEE' 'YLEL' 'DONRO' 'AALRYS' 'HAKMOCM']
 ['EYS' 'RADC' 'CLREK' 'EABLLT' 'GBRAAGE']
 ['ACN' 'LBLE' 'DONRO' 'RDFUNE' 'YUOEJRN']
 ['EYS' 'TBLE' 'PEOKR' 'WIZRAD' 'NAYUGHT']
 ['HWY' 'TBLE' 'VENGA' 'RDFUNE' 'GBRAAGE']
 ['APC' 'BTEL' 'VENGA' 'RDFUNE' 'YUOEJRN']
 ['YSE' 'LYLE' 'NPOHE' 'IEGWHT' 'JNOUREY']
 ['YEE' 'EDDE' 'OUIPM' 'CRABON' 'NAYUGHT']
 ['AHT' 'LYLE' 'VENGA' 'DOLRLA' 'CLEIMAT ']
 ['PCU' 'OWDR' 'GIATN' 'SADOWH' 'CLAIGER']
 ['WYH' 'LBLE' 'EVANG' 'HSOADW' 'GBRAAGE']
 ['TEH' 'WODR' 'DONRO' 'RODLLA' 'AXPLINE']
 ['APC' 'RADC' 'TELCE' 'BLLAET' 'NAYUGHT']
 ['CPA' 'DDEE' 'OONRD' 'NCRBOA' 'AYKAWLJ']
 ['NUF' 'TIPN' 'DONRO' 'RAODNM' 'CLEIMAT ']
 ['FNU' 'STRO' 'VENGA' 'NCRBOA' 'AXPLINE']
 ['FNU' 'BTEL' 'IGNAT' 'WEIGTH' 'AYKAWLJ']
 ['WYH' 'STRO' 'SAOSI' 'ZIAWRD' 'HAKMOCM']
 ['UNS' 'TIPN' 'OUIPM' 'IEGWHT' 'JNOUREY']
 ['EEY' 'PTIN' 'POUIM' 'HSOADW' 'JNOUREY']
 ['YEE' 'DIFN' 'SCELA' 'EABLLT' 'HAKMOCM']
 ['TEH' '